In [10]:
import numpy as np

In [14]:
# buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[2, 5, 1],
              [0, 5, 3]])
x

array([[2, 5, 1],
       [0, 5, 3]])

In [18]:
# tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [21]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x[0:, 0]

array([2, 0])

In [23]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[1:,]

array([[0, 5, 3]])

In [24]:
# ulangi soal nomor 1 menggunakan pytorch
import torch
x_pt = torch.tensor([[2, 5, 1],
                     [0, 5, 3]])
x_pt

tensor([[2, 5, 1],
        [0, 5, 3]])

In [26]:
x_pt.shape

torch.Size([2, 3])

In [28]:
x_pt[0:, 0]

tensor([2, 0])

In [29]:
x_pt[1:,]

tensor([[0, 5, 3]])

In [31]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf
x_tf = tf.Variable([[2, 5, 1],
                    [0, 5, 3]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 5, 1],
       [0, 5, 3]], dtype=int32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 5, 1],
       [0, 5, 3]], dtype=int32)>

In [33]:
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [34]:
x_tf[0:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0], dtype=int32)>

In [36]:
x_tf[1:, ]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[0, 5, 3]], dtype=int32)>