In [ ]:
import numpy as np

In [ ]:
# buat vector x dengan ukuran 3x1
x = np.array([[0],
              [5],
              [3]])
x

array([[0],
       [5],
       [3]])

In [ ]:
# hitung panjang vector x
len(x)

3

In [ ]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [ ]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [ ]:
# akses elemen pertama dari vector x
x[0]

array([0])

In [ ]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0,0])

numpy.int64

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[0, 5, 3]])

In [ ]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [ ]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array ([[1, 2, 3],
              [4, 5, 6]])
y_t = y.T
y_t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# tampilkan ukuran dari vector x_t
x.T.shape

(1, 3)

In [ ]:
import torch
import tensorflow as tf

In [ ]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
x_pt = torch.tensor([[0],
                     [5],
                     [3]])
x_pt

tensor([[0],
        [5],
        [3]])

In [18]:
x_tf = tf.Variable([[0],
                    [5],
                    [3]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[0],
       [5],
       [3]], dtype=int32)>